v0.99.10 -- No longer depends on find_geo() for the vignette
Seems like a recent change in one of the packages recount suggests broke
something. That's evident from https://github.com/leekgroup/recount/tree/67b47755c474b690ae86e946188b596dfef6bc36
which did work with recount 0.99.9. The packages that changed are (from
comparing the above session information to the one included later in this
commit message):

* BiocGenerics: 0.19.0 to 0.19.1
* GenomicRanges: 1.25.1 to 1.25.4
* IRanges: 2.7.4 to 2.7.6
* S4Vectors: 0.11.3 to 0.11.4
* SummarizedExperiment from 1.3.3 to 1.3.4

In any case, now there is a weird error when building recount:

```
Quitting from lines 268-298 (recount-quickstart.Rmd)
Error: processing vignette 'recount-quickstart.Rmd' failed with diagnostics:
"characteristics" %in% colnames(pheno) is not TRUE
```

This error does not appear when using the recount 0.99.9 and running code from
the vignette interactively. It seems like when using
`R CMD build --no-manual --no-resave-data recount` find_geo() does not work
for all samples. Interactively, the result is:

```
> geoids
  SRR387777   SRR387778   SRR387779   SRR387780   SRR389077   SRR389078   SRR389079   SRR389080   SRR389081   SRR389082
"GSM836270" "GSM836271" "GSM836272" "GSM836273" "GSM847561" "GSM847562" "GSM847563" "GSM847564" "GSM847565" "GSM847566"
  SRR389083   SRR389084
"GSM847567" "GSM847568"
> options(width = 120)
> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------
 setting  value
 version  R version 3.3.0 RC (2016-05-01 r70572)
 system   x86_64, darwin13.4.0
 ui       AQUA
 language (EN)
 collate  en_US.UTF-8
 tz       America/New_York
 date     2016-06-12

Packages ---------------------------------------------------------------------------------------------------------------
 package              * version  date       source
 Biobase              * 2.33.0   2016-05-05 Bioconductor
 BiocGenerics         * 0.19.1   2016-06-11 Bioconductor
 bitops                 1.0-6    2013-08-17 CRAN (R 3.3.0)
 devtools               1.11.1   2016-04-21 CRAN (R 3.3.0)
 digest                 0.6.9    2016-01-08 CRAN (R 3.3.0)
 GenomeInfoDb         * 1.9.1    2016-05-13 Bioconductor
 GenomicRanges        * 1.25.4   2016-06-10 Bioconductor
 GEOquery             * 2.39.3   2016-05-20 Bioconductor
 httr                   1.1.0    2016-01-28 CRAN (R 3.3.0)
 IRanges              * 2.7.6    2016-06-10 Bioconductor
 memoise                1.0.0    2016-01-29 CRAN (R 3.3.0)
 R6                     2.1.2    2016-01-26 CRAN (R 3.3.0)
 RCurl                  1.95-4.8 2016-03-01 CRAN (R 3.3.0)
 recount              * 0.99.9   2016-06-12 Bioconductor
 S4Vectors            * 0.11.4   2016-06-11 Bioconductor
 SummarizedExperiment * 1.3.4    2016-06-10 Bioconductor
 withr                  1.0.1    2016-02-04 CRAN (R 3.3.0)
 XML                  * 3.98-1.4 2016-03-01 CRAN (R 3.3.0)
 XVector                0.13.0   2016-05-05 Bioconductor
 zlibbioc               1.19.0   2016-05-05 Bioconductor
```

Since this error does not occur when running the code interactively, I do not
know how to trace it back. It did happen every time I used `R CMD build` (about
4 times).

Version 0.99.10 no longer runs find_geo() in the vignette, which removes this
weird error. In any case, in a week or two, all RSE objects will have this
information and at that point find_geo() and geo_info() won't be needed for
the vignette.